### ISSUE TITLE
Missing file t5.json

### ISSUE THREAD

**Issue by limzykenneth** [koundinyad/translator#1]
@koundinyad I've only just got around to fully testing this but I am encountering some errors:

```
Error reading files: [Error: ENOENT: no such file or directory, open '../src/content/t5.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../src/content/t5.json'
}
```
and that the translation page are all blank with no entries in them. Does that file need to be generated somehow?

**Comment by limzykenneth** [comment]
I've created a t5.json file in `../src/content` with a blank array, not sure if that is the intent.

**Comment by koundinyad** [comment]
There was a bug in writing/updating the t5.json file on first read. Pushed a new commit to fix that

**Comment by koundinyad** [comment]
the file is only to keep a surface record for status tracking. Would be ideal to make it optional, since it writes to the original repository.
